apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adservice
  description: Ad Service for Online Boutique
  tags:
    - java
    - backend
    - grpc
  links:
    - url: https://github.com/googlecloudplatform/microservices-demo
      title: Online Boutique - Upstream repo
      icon: help
  annotations:
    'backstage.io/kubernetes-id': adservice
    'google.com/cloudbuild-project-slug': cpet-backstage
    'backstage.io/techdocs-ref': dir:../adservice/src
spec:
  type: service
  lifecycle: experimental
  owner: group:default/cpet-core
  system: online-boutique
  subcomponentof:
    - system:online-boutique
  # dependsOn: ['component:artists-db']
  apiConsumedBy: ['component:frontend']